//@version=5
indicator("T3-CCI MatheyBTC", shorttitle="T3-CCI", overlay=false)
CCI_Period = input.int(35, minval=1, title="CCI Period")
T3_Period = input.int(7, minval=1, title="T3 Period")
b = input.float(0.618, title="b")
xPrice = close
b2 = b * b
b3 = b2 * b
c1 = -b3
c2 = 3 * (b2 + b3)
c3 = -3 * (2 * b2 + b + b3)
c4 = 1 + 3 * b + b3 + 3 * b2
nn = T3_Period < 1 ? 1 : T3_Period
nr = 1 + 0.5 * (nn - 1)
w1 = 2 / (nr + 1)
w2 = 1 - w1
xcci = ta.cci(xPrice, CCI_Period)
var float e1 = 0.0
var float e2 = 0.0
var float e3 = 0.0
var float e4 = 0.0
var float e5 = 0.0
var float e6 = 0.0
e1 := w1 * xcci + w2 * nz(e1[1])
e2 := w1 * e1 + w2 * nz(e2[1])
e3 := w1 * e2 + w2 * nz(e3[1])
e4 := w1 * e3 + w2 * nz(e4[1])
e5 := w1 * e4 + w2 * nz(e5[1])
e6 := w1 * e5 + w2 * nz(e6[1])
xccir = c1 * e6 + c2 * e5 + c3 * e4 + c4 * e3
cciHcolor = xccir >= 0 ? color.green : color.red
var int pos = 0
pos := xccir > 0 ? 1 : xccir < 0 ? -1 : nz(pos[1], 0)
hline(0, color=color.purple, linestyle=hline.style_solid)
barcolor(pos == -1 ? color.red : pos == 1 ? color.green : color.blue)
plot(xccir, color=color.blue, title="T3-CCI")
plot(xccir, color=cciHcolor, title="CCIH", style=plot.style_histogram)
buySignal = ta.crossover(xccir, 0)
sellSignal = ta.crossunder(xccir, 0)
alertcondition(buySignal, title="T3-CCI COMPRA", message="COMPRA")
alertcondition(sellSignal, title="T3-CCI VENTA", message="VENTA")
